'use client';
import { useEffect, useMemo, useState } from 'react';
import { Download, Lock, LogOut, Search, ShieldCheck, Trash2, Upload, X } from 'lucide-react';

type Material={id:string;category:string;product_name:string;material_type:string;title:string;file_url:string;storage_path:string;file_type:string;created_at:string};
type Tool={title:string;desc:string;category:string};
const ADMIN_ID='admin';
const ADMIN_PW='admin1234';
const categories=['전체자료','학술임상','영업제안','브랜드홍보','IT솔루션','검사홍보'];
const materialTypes=['브로슈어','리플렛','뉴스레터','배너','탁상배너','포스터'];
const defaultTools:Tool[]=[
['의료진세미나','학술 PPT 세트','학술임상'],['AI세미나','디지털 헬스케어 자료','학술임상'],['임상컨설팅','검사 패널 제안','학술임상'],['인포노트','심층 임상 자료','학술임상'],['ATOZ','학술 백과사전','학술임상'],['주간질병감시','질환 동향 리포트','학술임상'],['고시ON','고시 변경 안내','학술임상'],
['SCD','성과 지표 리포트','영업제안'],['보험컨설팅','수가/청구 가이드','영업제안'],['축약제안서','요약 제안서','영업제안'],['표준제안서','재단 표준 영업 제안서','영업제안'],['종병제안서','종합병원 제안서','영업제안'],['병리과제안서','병리 특화 제안서','영업제안'],['소청제안서','소아청소년과 제안서','영업제안'],
['재단현판','공식 현판 시안','브랜드홍보'],['MINI CATALOGUE','휴대용 카탈로그','브랜드홍보'],['홈피','공식 웹사이트','브랜드홍보'],['언론/블로그','우수성 홍보 자료','브랜드홍보'],['검사홍보동영상','환자 안내 영상','브랜드홍보'],['스크린용PPT슬라이드영상','대기실 안내 영상','브랜드홍보'],
['One FOCUS','스마트 솔루션','IT솔루션'],['ONE CHART','자동 매핑 시스템','IT솔루션'],['ONE PLUS','경영 지원 플랫폼','IT솔루션'],['씨차트','차세대 클라우드 EMR','IT솔루션'],['DR.EMR','HIS 연동 가이드','IT솔루션'],
['SeeNIPT','비침습 산전 선별검사 홍보자료','검사홍보'],['MAST','알레르기 다중항원 동시검사 홍보자료','검사홍보']
].map(([title,desc,category])=>({title,desc,category}));

export default function Page(){
 const [materials,setMaterials]=useState<Material[]>([]),[cat,setCat]=useState('전체자료'),[query,setQuery]=useState(''),[page,setPage]=useState(1),[selected,setSelected]=useState<Tool|null>(null),[active,setActive]=useState<Material|null>(null);
 const [admin,setAdmin]=useState(false),[loginOpen,setLoginOpen]=useState(false),[adminId,setAdminId]=useState(''),[adminPw,setAdminPw]=useState('');
 useEffect(()=>{ setAdmin(localStorage.getItem('sg_admin')==='1'); loadMaterials(); },[]);
 async function loadMaterials(){ const r=await fetch('/api/materials',{cache:'no-store'}); const j=await r.json(); setMaterials(j.materials||[]); }
 function adminLogin(){ if(adminId===ADMIN_ID&&adminPw===ADMIN_PW){ localStorage.setItem('sg_admin','1'); setAdmin(true); setLoginOpen(false); setAdminId(''); setAdminPw(''); } else alert('관리자 계정이 올바르지 않습니다.'); }
 function adminLogout(){ localStorage.removeItem('sg_admin'); setAdmin(false); }
 const tools=useMemo(()=>{ const dynamic=[...new Set(materials.map(m=>m.product_name))].filter(t=>!defaultTools.some(d=>d.title===t)).map(t=>({title:t,desc:'등록 자료',category:materials.find(m=>m.product_name===t)?.category||'검사홍보'})); return [...defaultTools,...dynamic]; },[materials]);
 const filtered=tools.filter(t=>(cat==='전체자료'||t.category===cat)&&(`${t.title} ${t.desc}`.toLowerCase().includes(query.toLowerCase()))); const pages=Math.max(1,Math.ceil(filtered.length/15)); const shown=filtered.slice((page-1)*15,page*15);
 const selectedMaterials=selected?materials.filter(m=>m.product_name===selected.title):[];
 return <main className="wrap">
  <section className="hero"><div><div className="eyebrow">SEEGENE MEDICAL FOUNDATION</div><h1>씨젠의료재단 마케팅 포털</h1><p>학술·영업·검사홍보 자료를 한 곳에서 확인하는 통합 라이브러리</p></div><div className="heroRight">{admin?<><span className="adminBadge"><ShieldCheck size={16}/> 관리자 모드</span><button className="btn ghost" onClick={adminLogout}><LogOut size={16}/> 관리자 로그아웃</button></>:<button className="btn dark" onClick={()=>setLoginOpen(true)}><Lock size={16}/> 관리자 로그인</button>}</div></section>
  <section className="toolbar"><div className="search"><Search size={18}/><input placeholder="자료명 검색" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}}/></div><div className="chips">{categories.map(c=><button key={c} className={cat===c?'chip on':'chip'} onClick={()=>{setCat(c);setPage(1)}}>{c}</button>)}</div></section>
  {admin&&<AdminPanel materials={materials} reload={loadMaterials}/>} 
  <section className="grid5">{shown.map(t=><article className="card" key={t.title} onClick={()=>{setSelected(t); setActive(materials.find(m=>m.product_name===t.title)||null)}}><div className="cover"><span>{t.title.slice(0,8)}</span></div><div className="cardbody"><span className="badge">{t.category}</span><h3>{t.title}</h3><p>{t.desc}</p><div className="count">보유자료 {materials.filter(m=>m.product_name===t.title).length}건</div></div></article>)}</section>
  <div className="pager">{Array.from({length:pages},(_,i)=><button key={i} className={page===i+1?'chip on':'chip'} onClick={()=>setPage(i+1)}>{i+1}</button>)}</div>
  <Footer/>
  {loginOpen&&<div className="overlay"><div className="loginBox"><button className="close" onClick={()=>setLoginOpen(false)}><X/></button><h2>관리자 로그인</h2><p className="muted">자료 업로드/삭제는 관리자만 가능합니다.</p><input className="input" placeholder="ID" value={adminId} onChange={e=>setAdminId(e.target.value)}/><input className="input" type="password" placeholder="비밀번호" value={adminPw} onChange={e=>setAdminPw(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')adminLogin()}}/><button className="btn primary full" onClick={adminLogin}>로그인</button><p className="muted">기본 계정: admin / admin1234</p></div></div>}
  {selected&&<MaterialModal tool={selected} materials={selectedMaterials} active={active} setActive={setActive} close={()=>{setSelected(null);setActive(null)}} admin={admin} reload={loadMaterials}/>} 
 </main>;
}

function AdminPanel({materials,reload}:{materials:Material[],reload:()=>Promise<void>}){ const [category,setCategory]=useState('검사홍보'),[product,setProduct]=useState('SeeNIPT'),[type,setType]=useState('브로슈어'),[title,setTitle]=useState(''),[file,setFile]=useState<File|null>(null),[loading,setLoading]=useState(false);
 async function upload(){ if(!file) return alert('파일을 선택하세요.'); setLoading(true); try{ const f=new FormData(); f.append('category',category); f.append('product_name',product); f.append('material_type',type); f.append('title',title||`${product} ${type}`); f.append('file',file); const r=await fetch('/api/upload',{method:'POST',body:f}); const j=await r.json(); if(!r.ok) throw new Error(j.error||'업로드 실패'); setFile(null); setTitle(''); await reload(); alert('업로드 완료'); }catch(e:any){alert(e.message)} finally{setLoading(false)} }
 return <section className="adminPanel"><div><h2>자료 업로드</h2><p>PDF/JPG/PNG 파일을 Supabase Storage에 저장하고 대시보드에 즉시 반영합니다.</p><div className="formgrid"><select className="input" value={category} onChange={e=>setCategory(e.target.value)}>{categories.filter(c=>c!=='전체자료').map(c=><option key={c}>{c}</option>)}</select><input className="input" value={product} onChange={e=>setProduct(e.target.value)} placeholder="자료명 예: MAST"/><select className="input" value={type} onChange={e=>setType(e.target.value)}>{materialTypes.map(t=><option key={t}>{t}</option>)}</select><input className="input" value={title} onChange={e=>setTitle(e.target.value)} placeholder="표시 제목"/></div><label className="drop"><Upload/> <b>{file?file.name:'파일 선택 또는 드래그'}</b><input type="file" accept="application/pdf,image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button className="btn primary" disabled={loading} onClick={upload}>{loading?'업로드 중...':'업로드'}</button></div><div><h3>최근 등록 자료</h3><div className="miniList">{materials.slice(0,8).map(m=><div className="mini" key={m.id}><b>{m.product_name}</b><span>{m.material_type} · {m.title}</span></div>)}</div></div></section> }

function MaterialModal({tool,materials,active,setActive,close,admin,reload}:any){ async function del(m:Material){ if(!confirm('삭제할까요?')) return; const r=await fetch('/api/delete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:m.id})}); const j=await r.json(); if(!r.ok) return alert(j.error||'삭제 실패'); await reload(); const remain=materials.filter((x:Material)=>x.id!==m.id); setActive(remain[0]||null); }
 return <div className="modal"><div className="modalbox"><div className="viewer"><div className="modalHead"><div><span className="badge">{tool.category}</span><h2>{tool.title}</h2><p>{tool.desc}</p></div><button className="close" onClick={close}><X/></button></div>{active?<div className="preview"><div className="previewTop"><h3>{active.material_type} · {active.title}</h3><div className="row"><a className="btn primary" href={active.file_url} target="_blank" download><Download size={16}/> 다운로드</a>{admin&&<button className="btn danger" onClick={()=>del(active)}><Trash2 size={16}/> 삭제</button>}</div></div>{active.file_type?.includes('image')?<img src={active.file_url}/>:<iframe src={active.file_url}/>}</div>:<div className="empty"><h3>등록된 자료가 없습니다.</h3><p>관리자가 자료를 업로드하면 이곳에 표시됩니다.</p></div>}</div><aside className="side"><h3>보유자료 {materials.length}건</h3>{materials.length?<div className="materialList">{materials.map((m:Material)=><button key={m.id} className={active?.id===m.id?'material on':'material'} onClick={()=>setActive(m)}><b>{m.material_type}</b><span>{m.title}</span><small>{new Date(m.created_at).toLocaleDateString()}</small></button>)}</div>:<p className="muted">등록된 자료가 없습니다.</p>}</aside></div></div> }
function Footer(){return <footer className="footer"><h3>씨젠의료재단 학술문의 1566-6500</h3><div className="footgrid"><div><b>서울본원검사센터</b><br/>서울특별시 성동구 천호대로 320</div><div><b>대전충청검사센터</b><br/>대전광역시 대덕구 계족산로 81번길 87</div><div><b>대구경북검사센터</b><br/>대구광역시 수성구 달구벌대로 2619</div><div><b>광주호남검사센터</b><br/>광주광역시 남구 효우로 200</div><div><b>부산경남검사센터</b><br/>부산광역시 동구 중앙대로 297</div></div></footer>}
