'use client';
import { useEffect, useMemo, useState } from 'react';
import { getSupabase } from '@/lib/supabaseClient';
import { Download, LogOut, ShieldCheck, Upload, Users, X, Trash2 } from 'lucide-react';

type Profile={id:string;email:string;name:string|null;department:string|null;status:'pending'|'approved'|'rejected';role:'admin'|'employee'|'guest'};
type Material={id:string;category:string;product_name:string;material_type:string;title:string;file_url:string;storage_path:string;file_type:string;created_at:string};
const categories=['전체자료','학술임상','영업제안','브랜드홍보','IT솔루션','검사홍보'];
const defaultTools=[
['의료진세미나','학술 PPT 세트','학술임상'],['AI세미나','디지털 헬스케어 자료','학술임상'],['임상컨설팅','검사 패널 제안','학술임상'],['인포노트','심층 임상 자료','학술임상'],['ATOZ','학술 백과사전','학술임상'],['주간질병감시','질환 동향 리포트','학술임상'],['고시ON','고시 변경 안내','학술임상'],
['SCD','성과 지표 리포트','영업제안'],['보험컨설팅','수가/청구 가이드','영업제안'],['축약제안서','요약 제안서','영업제안'],['표준제안서','재단 표준 영업 제안서','영업제안'],['종병제안서','종합병원 제안서','영업제안'],['병리과제안서','병리 특화 제안서','영업제안'],['소청제안서','소아청소년과 제안서','영업제안'],
['재단현판','공식 현판 시안','브랜드홍보'],['MINI CATALOGUE','휴대용 카탈로그','브랜드홍보'],['홈피','공식 웹사이트','브랜드홍보'],['언론/블로그','우수성 홍보 자료','브랜드홍보'],['검사홍보동영상','환자 안내 영상','브랜드홍보'],['스크린용PPT슬라이드영상','대기실 안내 영상','브랜드홍보'],
['One FOCUS','스마트 솔루션','IT솔루션'],['ONE CHART','자동 매핑 시스템','IT솔루션'],['ONE PLUS','경영 지원 플랫폼','IT솔루션'],['씨차트','차세대 클라우드 EMR','IT솔루션'],['DR.EMR','HIS 연동 가이드','IT솔루션'],
['SeeNIPT','비침습 산전 선별검사 홍보자료','검사홍보'],['MAST','알레르기 다중항원 동시검사 홍보자료','검사홍보']
].map(([title,desc,category])=>({title,desc,category}));
const materialTypes=['브로슈어','리플렛','뉴스레터','배너','탁상배너','포스터'];

export default function Page(){
 const supabase = getSupabase();
 const [user,setUser]=useState<any>(null),[profile,setProfile]=useState<Profile|null>(null),[mode,setMode]=useState<'login'|'signup'>('login');
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[department,setDepartment]=useState('');
 const [materials,setMaterials]=useState<Material[]>([]),[cat,setCat]=useState('전체자료'),[query,setQuery]=useState(''),[page,setPage]=useState(1),[selected,setSelected]=useState<any>(null);
 const [active,setActive]=useState<Material|null>(null),[adminTab,setAdminTab]=useState<'upload'|'users'>('upload'),[users,setUsers]=useState<Profile[]>([]);
 const isAdmin=profile?.role==='admin'&&profile?.status==='approved'; const canDownload=profile?.role==='admin'||profile?.role==='employee';
 useEffect(()=>{ supabase.auth.getUser().then(({data})=>{ if(data.user) setUser(data.user); }); const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user||null)); return()=>subscription.unsubscribe();},[]);
 useEffect(()=>{ if(user) loadProfile(); },[user]);
 useEffect(()=>{ if(profile?.status==='approved') loadMaterials(); },[profile]);
 async function loadProfile(){ const {data}=await supabase.from('profiles').select('*').eq('id',user.id).single(); setProfile(data as any); }
 async function loadMaterials(){ const r=await fetch('/api/materials'); const j=await r.json(); setMaterials(j.materials||[]); }
 async function auth(){ if(mode==='login'){ const {error}=await supabase.auth.signInWithPassword({email,password}); if(error) alert(error.message); } else { const {data,error}=await supabase.auth.signUp({email,password}); if(error) return alert(error.message); if(data.user){ await fetch('/api/profile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId:data.user.id,email,name,department})}); alert('회원가입 신청 완료. 관리자 승인 후 이용 가능합니다.'); setMode('login'); } } }
 async function logout(){ await supabase.auth.signOut(); setUser(null); setProfile(null); }
 const tools=useMemo(()=>{ const dynamic=[...new Set(materials.map(m=>m.product_name))].filter(t=>!defaultTools.some(d=>d.title===t)).map(t=>({title:t,desc:'등록 자료',category:materials.find(m=>m.product_name===t)?.category||'검사홍보'})); return [...defaultTools,...dynamic]; },[materials]);
 const filtered=tools.filter(t=>(cat==='전체자료'||t.category===cat)&&(`${t.title} ${t.desc}`.toLowerCase().includes(query.toLowerCase()))); const pages=Math.max(1,Math.ceil(filtered.length/15)); const shown=filtered.slice((page-1)*15,page*15);
 const selectedMaterials=selected?materials.filter(m=>m.product_name===selected.title):[];
 useEffect(()=>{ if(selectedMaterials.length && !active) setActive(selectedMaterials[0]); },[selected]);
 if(!user) return <Auth mode={mode} setMode={setMode} email={email} setEmail={setEmail} password={password} setPassword={setPassword} name={name} setName={setName} department={department} setDepartment={setDepartment} auth={auth}/>;
 if(!profile) return <div className="wrap">프로필 확인 중...</div>;
 if(profile.status!=='approved') return <div className="auth panel"><h2>승인 대기 상태입니다.</h2><p className="small">관리자가 계정 등급을 지정하고 승인하면 이용 가능합니다.</p><button className="btn dark" onClick={logout}>로그아웃</button></div>;
 return <div className="wrap"><section className="hero"><div className="top"><div><div className="brand">씨젠의료재단 마케팅 포털</div><div className="sub">학술·영업·검사홍보 자료 통합 라이브러리</div></div><div className="row"><span>{profile.name||profile.email} · {roleName(profile.role)}</span>{isAdmin&&<button className="btn ghost" onClick={()=>setAdminTab(adminTab==='upload'?'users':'upload')}>{adminTab==='upload'?<Users size={16}/>:<Upload size={16}/>} 관리자</button>}<button className="btn ghost" onClick={logout}><LogOut size={16}/> 로그아웃</button></div></div></section>
 <div className="bar"><input className="input" style={{maxWidth:360}} placeholder="자료명 검색" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} />{categories.map(c=><button key={c} className={`chip ${cat===c?'on':''}`} onClick={()=>{setCat(c);setPage(1)}}>{c}</button>)}</div>
 {isAdmin&&<AdminPanel tab={adminTab} user={user} materials={materials} loadMaterials={loadMaterials} users={users} setUsers={setUsers}/>} 
 <div className="grid5">{shown.map(t=><div className="card" key={t.title} onClick={()=>{setSelected(t);setActive(materials.find(m=>m.product_name===t.title)||null)}}><div className="cover"><div className="doc">{t.title}</div></div><div className="cardbody"><span className="badge">{t.category}</span><div className="title">{t.title}</div><div className="desc">{t.desc}</div><p className="small">보유자료 {materials.filter(m=>m.product_name===t.title).length}건</p></div></div>)}</div>
 <div className="pager">{Array.from({length:pages},(_,i)=><button key={i} className={`chip ${page===i+1?'on':''}`} onClick={()=>setPage(i+1)}>{i+1}</button>)}</div>
 <Footer/>{selected&&<Modal tool={selected} materials={selectedMaterials} active={active} setActive={setActive} close={()=>{setSelected(null);setActive(null)}} canDownload={!!canDownload} isAdmin={!!isAdmin} user={user} reload={loadMaterials}/>}</div>;
}
function Auth(p:any){return <div className="auth panel"><h1>씨젠의료재단 마케팅 포털</h1><p className="small">로그인 또는 회원가입 신청</p><input className="input" placeholder="이메일" value={p.email} onChange={(e:any)=>p.setEmail(e.target.value)}/><br/><br/><input className="input" type="password" placeholder="비밀번호" value={p.password} onChange={(e:any)=>p.setPassword(e.target.value)}/>{p.mode==='signup'&&<><br/><br/><input className="input" placeholder="이름" value={p.name} onChange={(e:any)=>p.setName(e.target.value)}/><br/><br/><input className="input" placeholder="부서/지점" value={p.department} onChange={(e:any)=>p.setDepartment(e.target.value)}/></>}<br/><br/><button className="btn primary" style={{width:'100%'}} onClick={p.auth}>{p.mode==='login'?'로그인':'회원가입 신청'}</button><br/><br/><button className="btn ghost" style={{width:'100%'}} onClick={()=>p.setMode(p.mode==='login'?'signup':'login')}>{p.mode==='login'?'회원가입 신청하기':'로그인으로 돌아가기'}</button></div>}
function AdminPanel({tab,user,materials,loadMaterials,users,setUsers}:any){ const [category,setCategory]=useState('검사홍보'),[product,setProduct]=useState('SeeNIPT'),[type,setType]=useState('브로슈어'),[title,setTitle]=useState(''),[file,setFile]=useState<File|null>(null); async function upload(){ if(!file) return alert('파일을 선택하세요.'); const f=new FormData(); f.append('userId',user.id); f.append('category',category); f.append('product_name',product); f.append('material_type',type); f.append('title',title||`${product} ${type}`); f.append('file',file); const r=await fetch('/api/upload',{method:'POST',body:f}); const j=await r.json(); if(!r.ok) return alert(j.error); setFile(null); setTitle(''); await loadMaterials(); alert('업로드 완료'); } async function loadUsers(){const r=await fetch(`/api/users?userId=${user.id}`); const j=await r.json(); setUsers(j.users||[])} useEffect(()=>{if(tab==='users')loadUsers()},[tab]); if(tab==='users')return <div className="panel" style={{marginBottom:20}}><h2><ShieldCheck/> 회원관리</h2><div className="list">{users.map((u:Profile)=><UserRow key={u.id} u={u} adminId={user.id} reload={loadUsers}/>)}</div></div>; return <div className="panel admin" style={{marginBottom:20}}><div><h2>자료 업로드</h2><p className="small">PDF/JPG/PNG 파일을 Supabase Storage에 저장하고 대시보드에 즉시 반영합니다.</p><div className="row"><select className="input" value={category} onChange={e=>setCategory(e.target.value)}>{categories.filter(c=>c!=='전체자료').map(c=><option key={c}>{c}</option>)}</select><input className="input" value={product} onChange={e=>setProduct(e.target.value)} placeholder="자료명 예: MAST"/></div><br/><div className="row"><select className="input" value={type} onChange={e=>setType(e.target.value)}>{materialTypes.map(t=><option key={t}>{t}</option>)}</select><input className="input" value={title} onChange={e=>setTitle(e.target.value)} placeholder="표시 제목"/></div><br/><input className="input" type="file" accept="application/pdf,image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/><br/><br/><button className="btn primary" onClick={upload}>업로드</button></div><div><h3>최근 등록 자료</h3><div className="list">{materials.slice(0,6).map((m:Material)=><div className="item" key={m.id}>{m.product_name} · {m.material_type}<br/><span className="small">{m.title}</span></div>)}</div></div></div>}
function UserRow({u,adminId,reload}:any){const [role,setRole]=useState(u.role),[status,setStatus]=useState(u.status);async function save(){const r=await fetch('/api/users',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({adminId,targetId:u.id,role,status})}); if(r.ok){alert('저장 완료');reload()}else alert('저장 실패')}return <div className="item row" style={{justifyContent:'space-between'}}><div><b>{u.name||u.email}</b><br/><span className="small">{u.email} · {u.department||'-'}</span></div><select value={role} onChange={e=>setRole(e.target.value)}><option value="admin">관리자</option><option value="employee">직원</option><option value="guest">게스트</option></select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="pending">대기</option><option value="approved">승인</option><option value="rejected">거절</option></select><button className="btn dark" onClick={save}>저장</button></div>}
function Modal({tool,materials,active,setActive,close,canDownload,isAdmin,user,reload}:any){ async function del(m:Material){ if(!confirm('삭제할까요?'))return; const r=await fetch('/api/delete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId:user.id,id:m.id})}); if(r.ok){await reload(); close()}else alert('삭제 실패') } return <div className="modal"><div className="modalbox"><div className="viewer"><div className="row" style={{justifyContent:'space-between'}}><h2>{tool.title}</h2><button className="btn ghost" onClick={close}><X/></button></div>{active?<><h3>{active.material_type} · {active.title}</h3>{active.file_type?.includes('image')?<img src={active.file_url} style={{maxWidth:'100%',borderRadius:18}}/>:<iframe className="pdf" src={active.file_url}/>}<div className="row" style={{marginTop:12}}>{canDownload&&<a className="btn primary" href={active.file_url} download target="_blank">다운로드 <Download size={16}/></a>}{isAdmin&&<button className="btn danger" onClick={()=>del(active)}><Trash2 size={16}/> 삭제</button>}</div></>:<div className="panel"><h3>등록된 자료가 없습니다.</h3><p className="small">관리자가 자료를 업로드하면 이 영역에 표시됩니다.</p></div>}</div><aside className="side"><h3>보유자료 {materials.length}건</h3><div className="list">{materials.map((m:Material)=><div key={m.id} className={`item ${active?.id===m.id?'on':''}`} onClick={()=>setActive(m)}><b>{m.material_type}</b><br/><span>{m.title}</span><br/><span className="small">{new Date(m.created_at).toLocaleDateString()}</span></div>)}</div>{!canDownload&&<p className="small">게스트는 다운로드가 제한됩니다.</p>}</aside></div></div>}
function Footer(){return <footer className="footer"><h3>씨젠의료재단 학술문의 1566-6500</h3><div className="footgrid"><div><b>서울본원검사센터</b><br/>서울특별시 성동구 천호대로 320</div><div><b>대전충청검사센터</b><br/>대전광역시 대덕구 계족산로 81번길 87</div><div><b>대구경북검사센터</b><br/>대구광역시 수성구 달구벌대로 2619</div><div><b>광주호남검사센터</b><br/>광주광역시 남구 효우로 200</div><div><b>부산경남검사센터</b><br/>부산광역시 동구 중앙대로 297</div></div></footer>}
function roleName(r:string){return r==='admin'?'관리자':r==='employee'?'직원':'게스트'}
